# <font color=blue>Assignments for "Data Cleaning - Variable Types"</font>

**(1)** Determine the types of the below-given variables:
- Age
- Salary
- Income
- Customer type
- Stock price


*  Age - Continuous (Ratio)
*  Salary - Continuous (Ratio)
*  Income - Continuos (It can be ordinal)
*  Customer type - Nominal
*  Stock Price - Continuous (Ratio)

**(2)** Using the `movie` data, we have studied in this lesson. Complete the following tasks:
    * Select a variable from the `movie` dataset and discuss the variable type of this variable
    * Categorize a variable of your choice and assign a name to it
    * Count the number of rows for each category

In [2]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies_metadata.csv', low_memory=False)

In [3]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
import pandas as pd
import numpy as np

movies = pd.read_csv('https://djl-lms-assets.s3.eu-central-1.amazonaws.com/datasets/movie.csv')

HTTPError: HTTP Error 404: Not Found

In [ ]:
movies.head()

   color      director_name  ...  aspect_ratio  movie_facebook_likes
0  Color      James Cameron  ...          1.78                 33000
1  Color     Gore Verbinski  ...          2.35                     0
2  Color         Sam Mendes  ...          2.35                 85000
3  Color  Christopher Nolan  ...          2.35                164000
4    NaN        Doug Walker  ...           NaN                     0

[5 rows x 28 columns]

In [ ]:
movies[['budget']].describe()

             budget
count  4.551000e+03
mean   3.975262e+07
std    2.061149e+08
min    2.180000e+02
25%    6.000000e+06
50%    2.000000e+07
75%    4.500000e+07
max    1.221550e+10

In [ ]:
def categorizer(budget):
    if budget >= 45000000:
        return 'high'
    elif (budget > 6000000) and (budget < 45000000):
        return 'medium'
    else:
        return 'low'

In [ ]:
movies['budget_group'] = movies['budget'].apply(categorizer)
display(movies.head())
movies.groupby("budget_group")["budget"].count()

   color      director_name  ...  movie_facebook_likes  budget_group
0  Color      James Cameron  ...                 33000          high
1  Color     Gore Verbinski  ...                     0          high
2  Color         Sam Mendes  ...                 85000          high
3  Color  Christopher Nolan  ...                164000          high
4    NaN        Doug Walker  ...                     0           low

[5 rows x 29 columns]

budget_group
high      1139
low       1170
medium    2242
Name: budget, dtype: int64

**(3)** Is it possible to convert categorical variable into numerical one? If 
so, how can you make that?

Yes , it is even necessary .  Because , if our data contains categorical data, we must encode it to numbers before we can fit and evaluate a model.So, ml models can only work on numeric values. We can create dummy variables using the scikit learn library, we can do one hot encoding or label encoding

**(4)** While continuous data is generally preferred over discrete data, please indicate circumstances where discrete is the preferred data type although continuous data is available for the same characteristic.

In some cases it is more convenient to use discrete data as more memory is required to store float data.

**(5)** While continuous data is measured and attribute data is counted, there is sometimes confusion if some specific dataset should be considered continuous or attribute. Provide some examples of confusing datasets and your inference.

 Continuous data results from  measurement on a continuous scale such as length, weight.We cannot accept these data as discrete data, for example, we are never exactly 80 kilos. We may weigh 80.23 or 80.2333 kilos. Continuous data can broken down into smaller parts and still have meaning. Also the time variable can be a confusing variable .Time is a continuous concept and is never discrete.